name: Docker Publish For WhatIsMyIP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  publish_linux_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build . --file WhatIsMyIP/Dockerfile --tag ${{secrets.DOCKER_USER}}/whatismyip:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/whatismyip:latest
      
  publish_windows_image:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build . --file WhatIsMyIP/Dockerfile --tag ${{secrets.DOCKER_USER}}/whatismyip:latest-windows
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/whatismyip:latest-windows
